name: Trigger ODPEM OCR Service

on:
  schedule:
    # Runs at the top of every hour (e.g., 1:00, 2:00, 3:00)
    - cron: '0 * * * *'
  workflow_dispatch:
    # Allows you to run it manually from the "Actions" tab

jobs:
  trigger-runpod-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST Request to RunPod
        run: |
          curl -X POST "https://api.runpod.ai/v2/${{ secrets.RUNPOD_ENDPOINT_ID }}/run" \
          -H "Authorization: Bearer ${{ secrets.RUNPOD_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
                "input": {
                  "scrape_url": "https://www.odpem.org.jm/weather-alert-melissa/"
                }
              }'